defmodule TaniwhaWeb.SessionController do
  @moduledoc """
  Handles browser session creation and deletion for cookie-based auth.

  This controller is the HTTP endpoint for the `phx-trigger-action` form in
  `LoginLive`. It re-validates credentials, sets the session (with fixation
  prevention), and redirects accordingly.

  ## Routes

      post "/session", SessionController, :create
      delete "/session", SessionController, :delete
  """

  use TaniwhaWeb, :controller

  alias Taniwha.Auth.CredentialStore

  @doc """
  Authenticates the user and creates a new session on success.

  On success: renews the session (session fixation prevention), stores
  `user_id`, and redirects to `/`.

  On failure: redirects to `/login` with an error flash message.
  """
  @spec create(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def create(conn, %{"username" => username, "password" => password}) do
    case CredentialStore.authenticate(username, password) do
      {:ok, user} ->
        conn
        |> configure_session(renew: true)
        |> put_session("user_id", user.id)
        |> redirect(to: ~p"/")

      {:error, :invalid_credentials} ->
        conn
        |> put_flash(:error, "Invalid username or password.")
        |> redirect(to: ~p"/login")
    end
  end

  @doc """
  Creates a session from a short-lived passkey login token.

  Called via form POST from `LoginLive` after a successful WebAuthn assertion.
  The token is generated by `LoginLive` using `Phoenix.Token.sign/3` and expires
  in 30 seconds (prevents replay if the token is intercepted).

  On success: renews the session, stores `user_id`, redirects to `/`.
  On failure (invalid/expired token or unknown user): redirects to `/login`.
  """
  @spec create_from_passkey(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def create_from_passkey(conn, %{"passkey_token" => token}) do
    case Phoenix.Token.verify(TaniwhaWeb.Endpoint, "passkey_login", token, max_age: 30) do
      {:ok, user_id} ->
        case CredentialStore.get_user(user_id) do
          {:ok, user} ->
            conn
            |> configure_session(renew: true)
            |> put_session("user_id", user.id)
            |> redirect(to: ~p"/")

          {:error, :not_found} ->
            conn
            |> put_flash(:error, "Sign-in failed. Please try again.")
            |> redirect(to: ~p"/login")
        end

      {:error, _reason} ->
        conn
        |> put_flash(:error, "Sign-in failed. Please try again.")
        |> redirect(to: ~p"/login")
    end
  end

  def create_from_passkey(conn, _params) do
    conn
    |> put_flash(:error, "Sign-in failed. Please try again.")
    |> redirect(to: ~p"/login")
  end

  @doc """
  Destroys the current session and redirects to `/login`.
  """
  @spec delete(Plug.Conn.t(), map()) :: Plug.Conn.t()
  def delete(conn, _params) do
    conn
    |> clear_session()
    |> redirect(to: ~p"/login")
  end
end
